services:
  php:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: crackhub_php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - rede-crackhub

  mysql:
    image: mysql:8.0
    container_name: crackhub_mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha_root_123
      MYSQL_DATABASE: crackhub
      MYSQL_USER: usuario_app
      MYSQL_PASSWORD: senha_app_123
    volumes:
      - dados_mysql:/var/lib/mysql
      - ./Docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - rede-crackhub

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: crackhub_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: usuario_app
      PMA_PASSWORD: senha_app_123
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - rede-crackhub

volumes:
  dados_mysql: {}

networks:
  rede-crackhub:
    driver: bridge